changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    # If PR has multiple labels, it will be added to the first matching category
    - title: Breaking Changes 🛠
      labels:
        - kind/breaking-change
    - title: Exciting New Features 🎉
      labels:
        - kind/enhancement
        - kind/feature
    - title: Bug fixes 🐛
      labels:
        - kind/bug
    - title: Documentation Updates 📚
      labels:
        - kind/documentation
    - title: Other Changes 🔄
      labels:
        - "*"