/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EndpointApplyConfiguration represents a declarative configuration of the Endpoint type for use
// with apply.
//
// Endpoint describes a single statically configured model serving instance.
type EndpointApplyConfiguration struct {
	// Name uniquely identifies the endpoint within the ModelServer. Together with
	// the ModelServer name it forms the instance identity in the router, for
	// example in metrics and debug output.
	Name *string `json:"name,omitempty"`
	// Address is the IP address or DNS name of the model serving instance.
	Address *string `json:"address,omitempty"`
	// Port is the port the model serving instance listens on. It defaults to
	// `spec.workloadPort.port` when unset.
	Port *int32 `json:"port,omitempty"`
	// Labels are attached to the endpoint. They do not select serving instances;
	// they are only matched against `workloadSelector.pdGroup` to assign the
	// endpoint a prefill or decode role, `pdGroup` being the sole
	// `workloadSelector` field that may be combined with `endpoints`.
	Labels map[string]string `json:"labels,omitempty"`
}

// EndpointApplyConfiguration constructs a declarative configuration of the Endpoint type for use with
// apply.
func Endpoint() *EndpointApplyConfiguration {
	return &EndpointApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithName(value string) *EndpointApplyConfiguration {
	b.Name = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithAddress(value string) *EndpointApplyConfiguration {
	b.Address = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithPort(value int32) *EndpointApplyConfiguration {
	b.Port = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *EndpointApplyConfiguration) WithLabels(entries map[string]string) *EndpointApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}
