---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ai.kmesh.net
  resources:
  - ModelRoutes
  - ModelServers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.kmesh.net
  resources:
  - ModelRoutes/finalizers
  - ModelServers/finalizers
  verbs:
  - update
- apiGroups:
  - ai.kmesh.net
  resources:
  - ModelRoutes/status
  - ModelServers/status
  verbs:
  - get
  - patch
  - update
