name: Python Licenses Check

on:
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - "python/**"

jobs:
  python-licenses-lint:
    name: Python Licenses Lint
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install liccheck
        run: |
          python -m pip install --upgrade pip
          pip install liccheck
      - name: Check Runtime Requirements
        run: |
          if [ -f "python/kthena/runtime/requirements.txt" ]; then
            echo "🔍 Checking runtime requirements..."
            pip install -r python/kthena/runtime/requirements.txt
            liccheck -s config/python-licenses-lint.ini -r python/kthena/runtime/requirements.txt
            echo "✅ Runtime requirements check completed"
          else
            echo "⚠️  Runtime requirements file not found, skipping..."
          fi
      - name: Check Downloader Requirements
        run: |
          if [ -f "python/kthena/downloader/requirements.txt" ]; then
            echo "🔍 Checking downloader requirements..."
            pip install -r python/kthena/downloader/requirements.txt
            liccheck -s config/python-licenses-lint.ini -r python/kthena/downloader/requirements.txt
            echo "✅ Downloader requirements check completed"
          else
            echo "⚠️  Downloader requirements file not found, skipping..."
          fi
